### ISSUE TITLE
Publish to maven central?

### ISSUE THREAD

**Issue by mpkorstanje** [mikedon/encoding-enforcer#2]
I noticed this plugin is not available from maven central. This makes usage non-trivial. It is not too difficult to get yourselves published there if you use sonatype.

You will have to add an explicit open source license and change the groupId to something like com.github.mikedon because you don't own com.miked but that is about it.

See: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by ericbn** [comment]
Good idea. @mikedon is not activelly working on this anymore, but we can help. @mpkorstanje, do you have experience and the required environment to do this? I don't.

**Comment by mpkorstanje** [comment]
I've recently found that Mojohaus provides a plugin that seems to provide similar functionality. Haven't had a chance to try it out but it make publishing this single rule to central a duplication of efforts.

http://www.mojohaus.org/extra-enforcer-rules/requireEncoding.html

**Comment by mpkorstanje** [comment]
@ericbn and to answer your question. Yes. I do have that experience and environment setup. Using it for simmetrics at the moment.

**Comment by ericbn** [comment]
Thanks for the info, @mpkorstanje. So maybe we can deprecate this repo in favor of http://www.mojohaus.org/extra-enforcer-rules/requireEncoding.html.

**Comment by ericbn** [comment]
Just for "documenting" the difference:

mikedon:encoding-enforcer is using [juniversalchardet](https://mvnrepository.com/artifact/com.googlecode.juniversalchardet/juniversalchardet/) to do the encoding detection. And org.codehaus.mojo:extra-enforcer-rules uses [ICU4J](https://mvnrepository.com/artifact/com.ibm.icu/icu4j) to do it.

**Comment by mpkorstanje** [comment]
Yes I would reckon deprecation to be the best option. Seems that juniversalchardet is no longer actively supported.
